version: '2'

services:

  micro-frontend-docs-page:
    container_name: micro-frontend-docs-page
    build: docs-page
    environment:
      - NODE_ENV=production
      - PORT=3000

  micro-frontend-items-page:
    container_name: micro-frontend-items-page
    build: items-page
    environment:
      - NODE_ENV=production
      - PORT=4000
  
  micro-frontend-home-page:
    container_name: micro-frontend-home-page
    build: home-page
    environment:
      - NODE_ENV=production
      - PORT=5000

  micro-frontend-nginx:
    container_name: micro-frontend-nginx
    build: nginx
    volumes:
      - ./assets:/var/www
    ports:
      - "8888:80"
    links:
      - micro-frontend-home-page
      - micro-frontend-docs-page
      - micro-frontend-items-page
    depends_on:
      - micro-frontend-home-page
      - micro-frontend-docs-page
      - micro-frontend-items-page